# Version de la syntaxe du fichier docker-compose.
# Utilisez une version 3.8 ou supérieure pour prendre en charge Docker Swarm.
version: '3.8'

# Définition des services à déployer.
services:
  # Service pour Drupal.
  drupal:
    image: drupal:8-apache  # Utilise l'image officielle de Drupal 8 avec Apache.
    volumes:
      - drupal:/var/www/html  # Le volume persiste les fichiers de Drupal.
    ports:
      - "8080:80"  # Mappe le port 80 du conteneur sur le port 8080 de l'hôte.
    networks:
      - net  # Connecte le service au réseau Swarm 'net'.
    deploy:
      replicas: 4  # Exécute 4 réplicas du service pour la haute disponibilité.
      update_config:
        parallelism: 2  # Met à jour 2 conteneurs en parallèle lors des mises à jour.
        delay: 10s  # Intervalle de 10 secondes entre les mises à jour.
      restart_policy:
        condition: on-failure  # Redémarre uniquement en cas d'échec.
      placement:
        constraints:
          - node.role == worker  # Drupal s'exécute sur des nœuds worker pour éviter de surcharger le manager.

  # Service pour PostgreSQL.
  postgres:
    image: postgres:10  # Utilise l'image officielle de PostgreSQL version 10.
    environment:
      POSTGRES_USER: drupal_user  # Utilisateur PostgreSQL.
      POSTGRES_PASSWORD: drupal_password  # Mot de passe PostgreSQL.
      POSTGRES_DB: drupal_db  # Base de données pour Drupal.
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persiste les données de la base de données.
    networks:
      - net  # Connecte le service au réseau Swarm 'net'.
    deploy:
      replicas: 1  # Exécute une seule instance de PostgreSQL.
      placement:
        constraints:
          - node.role == manager  # PostgreSQL s'exécute uniquement sur un nœud manager.
      restart_policy:
        condition: on-failure  # Redémarre uniquement en cas d'échec.

# Définition des volumes persistants pour stocker les données.
volumes:
  drupal:
    driver: local  # Pilote de volume local pour Drupal.
  postgres_data:
    driver: local  # Pilote de volume local pour PostgreSQL.

# Définition des réseaux pour connecter les services.
networks:
  net:
    driver: overlay  # Réseau overlay pour la communication entre les nœuds du cluster Swarm.
